import Foundation
import Mockable

/// Repository protocol for storing provider settings (e.g., isEnabled state).
/// Tests use MockProviderSettingsRepository (generated by @Mockable).
/// App uses UserDefaultsProviderSettingsRepository.
@Mockable
public protocol ProviderSettingsRepository: Sendable {
    /// Gets the enabled state for a provider (defaults to true if not set)
    func isEnabled(forProvider id: String) -> Bool

    /// Sets the enabled state for a provider
    func setEnabled(_ enabled: Bool, forProvider id: String)

    /// Gets the enabled state for a provider with a custom default
    func isEnabled(forProvider id: String, defaultValue: Bool) -> Bool
}

/// Repository protocol for storing provider-specific configuration.
/// Tests use MockProviderConfigRepository (generated by @Mockable).
/// App uses UserDefaultsProviderConfigRepository.
@Mockable
public protocol ProviderConfigRepository: Sendable {
    /// Gets the custom config path for Z.ai (empty string = use default)
    func zaiConfigPath() -> String

    /// Sets the custom config path for Z.ai
    func setZaiConfigPath(_ path: String)

    /// Gets the environment variable name for GLM auth token (empty = no env fallback)
    func glmAuthEnvVar() -> String

    /// Sets the environment variable name for GLM auth token
    func setGlmAuthEnvVar(_ envVar: String)

    /// Gets the environment variable name for GitHub Copilot token (empty = no env fallback)
    func copilotAuthEnvVar() -> String

    /// Sets the environment variable name for GitHub Copilot token
    func setCopilotAuthEnvVar(_ envVar: String)
}

// MARK: - Default Implementation

public extension ProviderSettingsRepository {
    /// Default implementation that uses `true` as the default value
    func isEnabled(forProvider id: String) -> Bool {
        isEnabled(forProvider: id, defaultValue: true)
    }
}
