import Foundation
import Mockable

/// Repository protocol for storing provider settings (e.g., isEnabled state).
/// Tests use MockProviderSettingsRepository (generated by @Mockable).
/// App uses UserDefaultsProviderSettingsRepository.
@Mockable
public protocol ProviderSettingsRepository: Sendable {
    /// Gets the enabled state for a provider (defaults to true if not set)
    func isEnabled(forProvider id: String) -> Bool

    /// Sets the enabled state for a provider
    func setEnabled(_ enabled: Bool, forProvider id: String)

    /// Gets the enabled state for a provider with a custom default
    func isEnabled(forProvider id: String, defaultValue: Bool) -> Bool
}

/// Z.ai-specific settings repository, extending base ProviderSettingsRepository.
/// Tests can use UserDefaultsProviderSettingsRepository with test UserDefaults.
/// App uses UserDefaultsProviderSettingsRepository.
public protocol ZaiSettingsRepository: ProviderSettingsRepository {
    /// Gets the custom config path for Z.ai (empty string = use default)
    func zaiConfigPath() -> String

    /// Sets the custom config path for Z.ai
    func setZaiConfigPath(_ path: String)

    /// Gets the environment variable name for GLM auth token (empty = no env fallback)
    func glmAuthEnvVar() -> String

    /// Sets the environment variable name for GLM auth token
    func setGlmAuthEnvVar(_ envVar: String)
}

/// Copilot-specific settings repository, extending base ProviderSettingsRepository.
/// Includes both configuration and credentials for GitHub Copilot.
/// Tests can use UserDefaultsProviderSettingsRepository with test UserDefaults.
/// App uses UserDefaultsProviderSettingsRepository.
public protocol CopilotSettingsRepository: ProviderSettingsRepository {
    // MARK: - Configuration

    /// Gets the environment variable name for GitHub Copilot token (empty = no env fallback)
    func copilotAuthEnvVar() -> String

    /// Sets the environment variable name for GitHub Copilot token
    func setCopilotAuthEnvVar(_ envVar: String)

    // MARK: - Credentials

    /// Saves the GitHub token
    func saveGithubToken(_ token: String)

    /// Retrieves the GitHub token
    func getGithubToken() -> String?

    /// Deletes the GitHub token
    func deleteGithubToken()

    /// Checks if a GitHub token is saved
    func hasGithubToken() -> Bool

    /// Saves the GitHub username
    func saveGithubUsername(_ username: String)

    /// Retrieves the GitHub username
    func getGithubUsername() -> String?

    /// Deletes the GitHub username
    func deleteGithubUsername()
}

/// Bedrock-specific settings repository, extending base ProviderSettingsRepository.
/// Stores AWS profile name (not credentials) and region configuration.
/// Tests can use UserDefaultsProviderSettingsRepository with test UserDefaults.
/// App uses UserDefaultsProviderSettingsRepository.
public protocol BedrockSettingsRepository: ProviderSettingsRepository {
    // MARK: - AWS Profile

    /// Gets the AWS profile name (empty = use default profile)
    func awsProfileName() -> String

    /// Sets the AWS profile name
    func setAWSProfileName(_ name: String)

    // MARK: - Regions

    /// Gets the list of AWS regions to monitor for Bedrock usage
    func bedrockRegions() -> [String]

    /// Sets the list of AWS regions to monitor
    func setBedrockRegions(_ regions: [String])

    // MARK: - Budget

    /// Gets the daily budget for quota calculations (nil = no budget set)
    func bedrockDailyBudget() -> Decimal?

    /// Sets the daily budget for quota calculations
    func setBedrockDailyBudget(_ amount: Decimal?)
}

// MARK: - Default Implementation

public extension ProviderSettingsRepository {
    /// Default implementation that uses `true` as the default value
    func isEnabled(forProvider id: String) -> Bool {
        isEnabled(forProvider: id, defaultValue: true)
    }
}
