#!/usr/bin/env python3
"""Generate docs/README.md from the `description` frontmatter of each provider and feature doc.

Usage: scripts/gen-docs.py          write docs/README.md
       scripts/gen-docs.py --check  exit 1 if docs/README.md is stale
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(ROOT, "docs", "README.md")


def description(path):
    with open(path, encoding="utf-8") as f:
        match = re.match(r"---\n(.*?)\n---\n", f.read(), re.S)
    found = match and re.search(r"^description:\s*(.+)$", match.group(1), re.M)
    return found.group(1).strip() if found else ""


def table(group):
    rows = ["| Doc | What it's for |", "|---|---|"]
    for path in sorted(glob.glob(os.path.join(ROOT, "docs", group, "*", "README.md"))):
        name = os.path.basename(os.path.dirname(path))
        rows.append(f"| [{name}]({group}/{name}/README.md) | {description(path)} |")
    return "\n".join(rows)


def render():
    return f"""# ClaudeBar docs

<!-- GENERATED by scripts/gen-docs.py from docs/{{providers,features}}/*/README.md frontmatter. Do not edit. -->

Start with the [README](../README.md). Something broken? See [troubleshooting](troubleshooting.md).

## Providers

{table("providers")}

## Features

{table("features")}

Guides: [troubleshooting](troubleshooting.md) · [settings](settings.md) · [architecture](architecture/ARCHITECTURE.md) · [contributing](../CONTRIBUTING.md) · [documentation design](documentation-design/README.md)
"""


def main():
    content = render()
    if "--check" in sys.argv:
        current = open(OUTPUT, encoding="utf-8").read() if os.path.exists(OUTPUT) else ""
        if current != content:
            print("docs/README.md is stale; run scripts/gen-docs.py")
            return 1
        return 0
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
