import Foundation
import Quotas
import Mockable

/// Repository protocol for storing provider settings (e.g., isEnabled state).
/// Tests use MockProviderSettingsRepository (generated by @Mockable).
/// App uses UserDefaultsProviderSettingsRepository.
@Mockable
public protocol ProviderSettingsRepository: Sendable {
    /// Gets the enabled state for a provider (defaults to true if not set)
    func isEnabled(forProvider id: String) -> Bool

    /// Sets the enabled state for a provider
    func setEnabled(_ enabled: Bool, forProvider id: String)

    /// Gets the enabled state for a provider with a custom default
    func isEnabled(forProvider id: String, defaultValue: Bool) -> Bool

    /// Gets the custom card URL for a provider (nil if not set)
    func customCardURL(forProvider id: String) -> String?

    /// Sets the custom card URL for a provider (empty string or nil to remove)
    func setCustomCardURL(_ url: String?, forProvider id: String)

    /// The `kind` of the data source a provider uses — what Settings calls
    /// PROBE MODE. `nil` until the person picks one.
    func dataSourceKind(forProvider id: String) -> String?

    /// Saves the data source a provider uses.
    func setDataSourceKind(_ kind: String, forProvider id: String)

    /// A provider's on/off setting by name — `claude.cliFallbackEnabled` is
    /// `isOn("cliFallbackEnabled", forProvider: "claude")`. `nil` when never set.
    func isOn(_ setting: String, forProvider id: String) -> Bool?

    /// Saves a provider's on/off setting by name.
    func setOn(_ on: Bool, _ setting: String, forProvider id: String)

    /// Gets the user's provider display order as provider IDs, empty when the
    /// user never reordered. IDs missing from the list keep their registration
    /// position; IDs of providers that no longer exist are ignored.
    func providerOrder() -> [String]

    /// Persists the user's provider display order.
    /// An empty list clears the stored order.
    func setProviderOrder(_ order: [String])

    /// A provider-scope setting's value by name, kept as `<id>.<setting>` —
    /// `kimi.region` is `value("region", forProvider: "kimi")`. `nil` when
    /// never set. Never a secret: those live in the vault.
    func value(_ setting: String, forProvider id: String) -> String?

    /// Saves it; `nil` forgets it, so the setting's default applies.
    func setValue(_ value: String?, _ setting: String, forProvider id: String)

    /// Where the provider's CLI lives on this Mac, when the person chose one
    /// — *CLI location* (#210). `nil` means "find it as usual".
    func cliPath(forProvider id: String) -> String?

    /// Saves the CLI location; `nil` forgets it.
    func setCLIPath(_ path: String?, forProvider id: String)

    /// Gets the quota keys hidden for a provider (issue #140), e.g. a
    /// model-specific window the user never uses. Empty set = show all.
    /// Keys the probe no longer reports are ignored at read time.
    func hiddenQuotaKeys(forProvider id: String) -> Set<String>

    /// Sets the quota keys hidden for a provider (empty set shows all)
    func setHiddenQuotaKeys(_ keys: Set<String>, forProvider id: String)
}

public extension ProviderSettingsRepository {
    /// Default for conformers that keep no choice: the definition's default applies.
    func dataSourceKind(forProvider id: String) -> String? { nil }

    /// Default for conformers that keep no choice.
    func setDataSourceKind(_ kind: String, forProvider id: String) {}

    /// Default for conformers that keep no such setting.
    func isOn(_ setting: String, forProvider id: String) -> Bool? { nil }

    /// Default for conformers that keep no such setting.
    func setOn(_ on: Bool, _ setting: String, forProvider id: String) {}

    /// Default for conformers that keep no order: the registration order applies.
    func providerOrder() -> [String] { [] }

    /// Default for conformers that keep no order: nothing to persist.
    func setProviderOrder(_ order: [String]) {}
    /// Default for conformers that keep no such setting: its default applies.
    func value(_ setting: String, forProvider id: String) -> String? { nil }

    /// Default for conformers that keep no such setting.
    func setValue(_ value: String?, _ setting: String, forProvider id: String) {}

    /// Default for conformers that keep no such setting: find the CLI as usual.
    func cliPath(forProvider id: String) -> String? { nil }

    /// Default for conformers that keep no such setting.
    func setCLIPath(_ path: String?, forProvider id: String) {}

    /// Default for conformers that keep no such setting: every quota is watched.
    func hiddenQuotaKeys(forProvider id: String) -> Set<String> { [] }

    /// Default for conformers that keep no such setting.
    func setHiddenQuotaKeys(_ keys: Set<String>, forProvider id: String) {}
}

// MARK: - Default Implementation

public extension ProviderSettingsRepository {
    /// Default implementation that uses `true` as the default value
    func isEnabled(forProvider id: String) -> Bool {
        isEnabled(forProvider: id, defaultValue: true)
    }
}
